CREATE TABLE applications (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  deposit VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);